name: Eric Ladd
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8959
title: My Life
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#45c4b1'
    - '#d1d5e1'
    - '#017664'
    - '#151412'
    - '#999da8'
  brandStrength: 0.5
  lightness: 0.6875
  saturation: 0.9375
  rhythmicContrast: 0.25
purpose: []
